"""Add all users rows

Revision ID: 89743c33250b
Revises: 687e095423ce
Create Date: 2019-02-08 17:11:44.064172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89743c33250b'
down_revision = '687e095423ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
